version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: fly1ngfry/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    image: fly1ngfry/taski_frontend
    depends_on:
      - backend
    volumes:
      - static:/frontend_static
    command:  cp -r /app/build/. /frontend_static/



  gateway:
    image: fly1ngfry/taski_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80

